# TCL File Generated by Component Editor 17.1
# Thu Oct 18 14:38:22 BST 2018
# DO NOT MODIFY


# 
# 7Seg_Encoder "7Seg Encoder" v1.0
#  2018.10.18.14:38:22
# 7 Segment Encoder
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module 7Seg_Encoder
# 
set_module_property DESCRIPTION "7 Segment Encoder"
set_module_property NAME 7Seg_Encoder
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Spugs IO"
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "7Seg Encoder"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL Seg7Encoder
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file Seg7Encoder.sv SYSTEM_VERILOG PATH Seg7Encoder.sv TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point conduit_data
# 
add_interface conduit_data conduit end
set_interface_property conduit_data associatedClock ""
set_interface_property conduit_data associatedReset ""
set_interface_property conduit_data ENABLED true
set_interface_property conduit_data EXPORT_OF ""
set_interface_property conduit_data PORT_NAME_MAP ""
set_interface_property conduit_data CMSIS_SVD_VARIABLES ""
set_interface_property conduit_data SVD_ADDRESS_GROUP ""

add_interface_port conduit_data char writebyteenable Input 8
add_interface_port conduit_data seg readdata Output 8

